/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.ads;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.tencent.bean.TokenKey;

/**
 * AdsAddRequest
 */
public class AdsAddRequest implements TokenKey {
  @SerializedName("adgroup_id")
  private Long adgroupId = null;

  @SerializedName("adcreative_id")
  private Long adcreativeId = null;

  @SerializedName("ad_name")
  private String adName = null;

  @SerializedName("configured_status")
  private String configuredStatus = null;

  @SerializedName("impression_tracking_url")
  private String impressionTrackingUrl = null;

  @SerializedName("click_tracking_url")
  private String clickTrackingUrl = null;

  @SerializedName("feeds_interaction_enabled")
  private Boolean feedsInteractionEnabled = null;

  @SerializedName("account_id")
  private Long accountId = null;

  public AdsAddRequest adgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
    return this;
  }

  /**
   * Get adgroupId
   *
   * @return adgroupId
   */
  public Long getAdgroupId() {
    return adgroupId;
  }

  public void setAdgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
  }

  public AdsAddRequest adcreativeId(Long adcreativeId) {
    this.adcreativeId = adcreativeId;
    return this;
  }

  /**
   * Get adcreativeId
   *
   * @return adcreativeId
   */
  public Long getAdcreativeId() {
    return adcreativeId;
  }

  public void setAdcreativeId(Long adcreativeId) {
    this.adcreativeId = adcreativeId;
  }

  public AdsAddRequest adName(String adName) {
    this.adName = adName;
    return this;
  }

  /**
   * Get adName
   *
   * @return adName
   */
  public String getAdName() {
    return adName;
  }

  public void setAdName(String adName) {
    this.adName = adName;
  }

  public AdsAddRequest configuredStatus(String configuredStatus) {
    this.configuredStatus = configuredStatus;
    return this;
  }

  /**
   * Get configuredStatus
   *
   * @return configuredStatus
   */
  public String getConfiguredStatus() {
    return configuredStatus;
  }

  public void setConfiguredStatus(String configuredStatus) {
    this.configuredStatus = configuredStatus;
  }

  public AdsAddRequest impressionTrackingUrl(String impressionTrackingUrl) {
    this.impressionTrackingUrl = impressionTrackingUrl;
    return this;
  }

  /**
   * Get impressionTrackingUrl
   *
   * @return impressionTrackingUrl
   */
  public String getImpressionTrackingUrl() {
    return impressionTrackingUrl;
  }

  public void setImpressionTrackingUrl(String impressionTrackingUrl) {
    this.impressionTrackingUrl = impressionTrackingUrl;
  }

  public AdsAddRequest clickTrackingUrl(String clickTrackingUrl) {
    this.clickTrackingUrl = clickTrackingUrl;
    return this;
  }

  /**
   * Get clickTrackingUrl
   *
   * @return clickTrackingUrl
   */
  public String getClickTrackingUrl() {
    return clickTrackingUrl;
  }

  public void setClickTrackingUrl(String clickTrackingUrl) {
    this.clickTrackingUrl = clickTrackingUrl;
  }

  public AdsAddRequest feedsInteractionEnabled(Boolean feedsInteractionEnabled) {
    this.feedsInteractionEnabled = feedsInteractionEnabled;
    return this;
  }

  /**
   * Get feedsInteractionEnabled
   *
   * @return feedsInteractionEnabled
   */
  public Boolean isFeedsInteractionEnabled() {
    return feedsInteractionEnabled;
  }

  public void setFeedsInteractionEnabled(Boolean feedsInteractionEnabled) {
    this.feedsInteractionEnabled = feedsInteractionEnabled;
  }

  public AdsAddRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  @Override
  public String getTokenKey() {
    return String.valueOf(accountId);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
