/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.ads;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.tencent.bean.common.Adcreative;
import com.hyq0719.mktapi.tencent.bean.common.AuditSpecStruct;

import java.util.ArrayList;
import java.util.List;

/**
 * 返回结构
 */
public class AdsGetListStruct {
  @SerializedName("campaign_id")
  private Long campaignId = null;

  @SerializedName("adgroup_id")
  private Long adgroupId = null;

  @SerializedName("ad_id")
  private Long adId = null;

  @SerializedName("ad_name")
  private String adName = null;

  @SerializedName("adcreative_id")
  private Long adcreativeId = null;

  @SerializedName("adcreative")
  private Adcreative adcreative = null;

  @SerializedName("configured_status")
  private String configuredStatus = null;

  @SerializedName("system_status")
  private String systemStatus = null;

  @SerializedName("audit_spec")
  private List<AuditSpecStruct> auditSpec = null;

  @SerializedName("impression_tracking_url")
  private String impressionTrackingUrl = null;

  @SerializedName("click_tracking_url")
  private String clickTrackingUrl = null;

  @SerializedName("feeds_interaction_enabled")
  private Boolean feedsInteractionEnabled = null;

  @SerializedName("is_deleted")
  private Boolean isDeleted = null;

  @SerializedName("is_dynamic_creative")
  private Boolean isDynamicCreative = null;

  @SerializedName("created_time")
  private Long createdTime = null;

  @SerializedName("last_modified_time")
  private Long lastModifiedTime = null;

  @SerializedName("reject_message")
  private String rejectMessage = null;

  public AdsGetListStruct campaignId(Long campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * Get campaignId
   *
   * @return campaignId
   */
  public Long getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(Long campaignId) {
    this.campaignId = campaignId;
  }

  public AdsGetListStruct adgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
    return this;
  }

  /**
   * Get adgroupId
   *
   * @return adgroupId
   */
  public Long getAdgroupId() {
    return adgroupId;
  }

  public void setAdgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
  }

  public AdsGetListStruct adId(Long adId) {
    this.adId = adId;
    return this;
  }

  /**
   * Get adId
   *
   * @return adId
   */
  public Long getAdId() {
    return adId;
  }

  public void setAdId(Long adId) {
    this.adId = adId;
  }

  public AdsGetListStruct adName(String adName) {
    this.adName = adName;
    return this;
  }

  /**
   * Get adName
   *
   * @return adName
   */
  public String getAdName() {
    return adName;
  }

  public void setAdName(String adName) {
    this.adName = adName;
  }

  public AdsGetListStruct adcreativeId(Long adcreativeId) {
    this.adcreativeId = adcreativeId;
    return this;
  }

  /**
   * Get adcreativeId
   *
   * @return adcreativeId
   */
  public Long getAdcreativeId() {
    return adcreativeId;
  }

  public void setAdcreativeId(Long adcreativeId) {
    this.adcreativeId = adcreativeId;
  }

  public AdsGetListStruct adcreative(Adcreative adcreative) {
    this.adcreative = adcreative;
    return this;
  }

  /**
   * Get adcreative
   *
   * @return adcreative
   */
  public Adcreative getAdcreative() {
    return adcreative;
  }

  public void setAdcreative(Adcreative adcreative) {
    this.adcreative = adcreative;
  }

  public AdsGetListStruct configuredStatus(String configuredStatus) {
    this.configuredStatus = configuredStatus;
    return this;
  }

  /**
   * Get configuredStatus
   *
   * @return configuredStatus
   */
  public String getConfiguredStatus() {
    return configuredStatus;
  }

  public void setConfiguredStatus(String configuredStatus) {
    this.configuredStatus = configuredStatus;
  }

  public AdsGetListStruct systemStatus(String systemStatus) {
    this.systemStatus = systemStatus;
    return this;
  }

  /**
   * Get systemStatus
   *
   * @return systemStatus
   */
  public String getSystemStatus() {
    return systemStatus;
  }

  public void setSystemStatus(String systemStatus) {
    this.systemStatus = systemStatus;
  }

  public AdsGetListStruct auditSpec(List<AuditSpecStruct> auditSpec) {
    this.auditSpec = auditSpec;
    return this;
  }

  public AdsGetListStruct addAuditSpecItem(AuditSpecStruct auditSpecItem) {
    if (this.auditSpec == null) {
      this.auditSpec = new ArrayList<AuditSpecStruct>();
    }
    this.auditSpec.add(auditSpecItem);
    return this;
  }

  /**
   * Get auditSpec
   *
   * @return auditSpec
   */
  public List<AuditSpecStruct> getAuditSpec() {
    return auditSpec;
  }

  public void setAuditSpec(List<AuditSpecStruct> auditSpec) {
    this.auditSpec = auditSpec;
  }

  public AdsGetListStruct impressionTrackingUrl(String impressionTrackingUrl) {
    this.impressionTrackingUrl = impressionTrackingUrl;
    return this;
  }

  /**
   * Get impressionTrackingUrl
   *
   * @return impressionTrackingUrl
   */
  public String getImpressionTrackingUrl() {
    return impressionTrackingUrl;
  }

  public void setImpressionTrackingUrl(String impressionTrackingUrl) {
    this.impressionTrackingUrl = impressionTrackingUrl;
  }

  public AdsGetListStruct clickTrackingUrl(String clickTrackingUrl) {
    this.clickTrackingUrl = clickTrackingUrl;
    return this;
  }

  /**
   * Get clickTrackingUrl
   *
   * @return clickTrackingUrl
   */
  public String getClickTrackingUrl() {
    return clickTrackingUrl;
  }

  public void setClickTrackingUrl(String clickTrackingUrl) {
    this.clickTrackingUrl = clickTrackingUrl;
  }

  public AdsGetListStruct feedsInteractionEnabled(Boolean feedsInteractionEnabled) {
    this.feedsInteractionEnabled = feedsInteractionEnabled;
    return this;
  }

  /**
   * Get feedsInteractionEnabled
   *
   * @return feedsInteractionEnabled
   */
  public Boolean isFeedsInteractionEnabled() {
    return feedsInteractionEnabled;
  }

  public void setFeedsInteractionEnabled(Boolean feedsInteractionEnabled) {
    this.feedsInteractionEnabled = feedsInteractionEnabled;
  }

  public AdsGetListStruct isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   *
   * @return isDeleted
   */
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public AdsGetListStruct isDynamicCreative(Boolean isDynamicCreative) {
    this.isDynamicCreative = isDynamicCreative;
    return this;
  }

  /**
   * Get isDynamicCreative
   *
   * @return isDynamicCreative
   */
  public Boolean isIsDynamicCreative() {
    return isDynamicCreative;
  }

  public void setIsDynamicCreative(Boolean isDynamicCreative) {
    this.isDynamicCreative = isDynamicCreative;
  }

  public AdsGetListStruct createdTime(Long createdTime) {
    this.createdTime = createdTime;
    return this;
  }

  /**
   * Get createdTime
   *
   * @return createdTime
   */
  public Long getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(Long createdTime) {
    this.createdTime = createdTime;
  }

  public AdsGetListStruct lastModifiedTime(Long lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

  /**
   * Get lastModifiedTime
   *
   * @return lastModifiedTime
   */
  public Long getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(Long lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }

  public AdsGetListStruct rejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
    return this;
  }

  /**
   * Get rejectMessage
   *
   * @return rejectMessage
   */
  public String getRejectMessage() {
    return rejectMessage;
  }

  public void setRejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
