/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.adgroups;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.tencent.bean.TokenKey;

import java.util.ArrayList;
import java.util.List;

/**
 * AdgroupsUpdateBidAmountRequest
 */
public class AdgroupsUpdateBidAmountRequest implements TokenKey {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("update_bid_amount_spec")
  private List<UpdateBidAmountStruct> updateBidAmountSpec = null;

  public AdgroupsUpdateBidAmountRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public AdgroupsUpdateBidAmountRequest updateBidAmountSpec(
          List<UpdateBidAmountStruct> updateBidAmountSpec) {
    this.updateBidAmountSpec = updateBidAmountSpec;
    return this;
  }

  public AdgroupsUpdateBidAmountRequest addUpdateBidAmountSpecItem(
          UpdateBidAmountStruct updateBidAmountSpecItem) {
    if (this.updateBidAmountSpec == null) {
      this.updateBidAmountSpec = new ArrayList<UpdateBidAmountStruct>();
    }
    this.updateBidAmountSpec.add(updateBidAmountSpecItem);
    return this;
  }

  /**
   * Get updateBidAmountSpec
   *
   * @return updateBidAmountSpec
   */
  public List<UpdateBidAmountStruct> getUpdateBidAmountSpec() {
    return updateBidAmountSpec;
  }

  public void setUpdateBidAmountSpec(List<UpdateBidAmountStruct> updateBidAmountSpec) {
    this.updateBidAmountSpec = updateBidAmountSpec;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  @Override
  public String getTokenKey() {
    return String.valueOf(accountId);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
