/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.adgroups;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.tencent.bean.TokenKey;

import java.util.ArrayList;
import java.util.List;

/**
 * AdgroupsUpdateDatetimeRequest
 */
public class AdgroupsUpdateDatetimeRequest implements TokenKey {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("update_datetime_spec")
  private List<UpdateDatetimeStruct> updateDatetimeSpec = null;

  public AdgroupsUpdateDatetimeRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public AdgroupsUpdateDatetimeRequest updateDatetimeSpec(
    List<UpdateDatetimeStruct> updateDatetimeSpec) {
    this.updateDatetimeSpec = updateDatetimeSpec;
    return this;
  }

  public AdgroupsUpdateDatetimeRequest addUpdateDatetimeSpecItem(
    UpdateDatetimeStruct updateDatetimeSpecItem) {
    if (this.updateDatetimeSpec == null) {
      this.updateDatetimeSpec = new ArrayList<UpdateDatetimeStruct>();
    }
    this.updateDatetimeSpec.add(updateDatetimeSpecItem);
    return this;
  }

  /**
   * Get updateDatetimeSpec
   *
   * @return updateDatetimeSpec
   */
  public List<UpdateDatetimeStruct> getUpdateDatetimeSpec() {
    return updateDatetimeSpec;
  }

  public void setUpdateDatetimeSpec(List<UpdateDatetimeStruct> updateDatetimeSpec) {
    this.updateDatetimeSpec = updateDatetimeSpec;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  @Override
  public String getTokenKey() {
    return String.valueOf(accountId);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
