/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 商标
 */
public class AdcreativeCorporate {
  @SerializedName("corporate_name")
  private String corporateName = null;

  @SerializedName("corporate_img")
  private String corporateImg = null;

  public AdcreativeCorporate corporateName(String corporateName) {
    this.corporateName = corporateName;
    return this;
  }

  /**
   * Get corporateName
   *
   * @return corporateName
   */
  public String getCorporateName() {
    return corporateName;
  }

  public void setCorporateName(String corporateName) {
    this.corporateName = corporateName;
  }

  public AdcreativeCorporate corporateImg(String corporateImg) {
    this.corporateImg = corporateImg;
    return this;
  }

  /**
   * Get corporateImg
   *
   * @return corporateImg
   */
  public String getCorporateImg() {
    return corporateImg;
  }

  public void setCorporateImg(String corporateImg) {
    this.corporateImg = corporateImg;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
