/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 视频浮层按钮信息
 */
public class AdcreativeVideoPopupButton {
  @SerializedName("video_popup_button_text")
  private String videoPopupButtonText = null;

  @SerializedName("video_popup_button_url")
  private String videoPopupButtonUrl = null;

  public AdcreativeVideoPopupButton videoPopupButtonText(String videoPopupButtonText) {
    this.videoPopupButtonText = videoPopupButtonText;
    return this;
  }

  /**
   * Get videoPopupButtonText
   *
   * @return videoPopupButtonText
   */
  public String getVideoPopupButtonText() {
    return videoPopupButtonText;
  }

  public void setVideoPopupButtonText(String videoPopupButtonText) {
    this.videoPopupButtonText = videoPopupButtonText;
  }

  public AdcreativeVideoPopupButton videoPopupButtonUrl(String videoPopupButtonUrl) {
    this.videoPopupButtonUrl = videoPopupButtonUrl;
    return this;
  }

  /**
   * Get videoPopupButtonUrl
   *
   * @return videoPopupButtonUrl
   */
  public String getVideoPopupButtonUrl() {
    return videoPopupButtonUrl;
  }

  public void setVideoPopupButtonUrl(String videoPopupButtonUrl) {
    this.videoPopupButtonUrl = videoPopupButtonUrl;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
