/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 标签
 */
public class AdcreativeLabel {
  @SerializedName("coordinate_x")
  private Long coordinateX = null;

  @SerializedName("coordinate_y")
  private Long coordinateY = null;

  @SerializedName("direction")
  private String direction = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("landing_page_url")
  private String landingPageUrl = null;

  public AdcreativeLabel coordinateX(Long coordinateX) {
    this.coordinateX = coordinateX;
    return this;
  }

  /**
   * Get coordinateX
   *
   * @return coordinateX
   */
  public Long getCoordinateX() {
    return coordinateX;
  }

  public void setCoordinateX(Long coordinateX) {
    this.coordinateX = coordinateX;
  }

  public AdcreativeLabel coordinateY(Long coordinateY) {
    this.coordinateY = coordinateY;
    return this;
  }

  /**
   * Get coordinateY
   *
   * @return coordinateY
   */
  public Long getCoordinateY() {
    return coordinateY;
  }

  public void setCoordinateY(Long coordinateY) {
    this.coordinateY = coordinateY;
  }

  public AdcreativeLabel direction(String direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   *
   * @return direction
   */
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public AdcreativeLabel content(String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   *
   * @return content
   */
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public AdcreativeLabel landingPageUrl(String landingPageUrl) {
    this.landingPageUrl = landingPageUrl;
    return this;
  }

  /**
   * Get landingPageUrl
   *
   * @return landingPageUrl
   */
  public String getLandingPageUrl() {
    return landingPageUrl;
  }

  public void setLandingPageUrl(String landingPageUrl) {
    this.landingPageUrl = landingPageUrl;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
