/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * app行为定向
 */
public class AppBehavior {
  @SerializedName("object_type")
  private String objectType = null;

  @SerializedName("object_id_list")
  private List<Long> objectIdList = null;

  @SerializedName("time_window")
  private Long timeWindow = null;

  @SerializedName("act_id_list")
  private List<String> actIdList = null;

  public AppBehavior objectType(String objectType) {
    this.objectType = objectType;
    return this;
  }

  /**
   * Get objectType
   *
   * @return objectType
   */
  public String getObjectType() {
    return objectType;
  }

  public void setObjectType(String objectType) {
    this.objectType = objectType;
  }

  public AppBehavior objectIdList(List<Long> objectIdList) {
    this.objectIdList = objectIdList;
    return this;
  }

  public AppBehavior addObjectIdListItem(Long objectIdListItem) {
    if (this.objectIdList == null) {
      this.objectIdList = new ArrayList<Long>();
    }
    this.objectIdList.add(objectIdListItem);
    return this;
  }

  /**
   * Get objectIdList
   *
   * @return objectIdList
   */
  public List<Long> getObjectIdList() {
    return objectIdList;
  }

  public void setObjectIdList(List<Long> objectIdList) {
    this.objectIdList = objectIdList;
  }

  public AppBehavior timeWindow(Long timeWindow) {
    this.timeWindow = timeWindow;
    return this;
  }

  /**
   * Get timeWindow
   *
   * @return timeWindow
   */
  public Long getTimeWindow() {
    return timeWindow;
  }

  public void setTimeWindow(Long timeWindow) {
    this.timeWindow = timeWindow;
  }

  public AppBehavior actIdList(List<String> actIdList) {
    this.actIdList = actIdList;
    return this;
  }

  public AppBehavior addActIdListItem(String actIdListItem) {
    if (this.actIdList == null) {
      this.actIdList = new ArrayList<String>();
    }
    this.actIdList.add(actIdListItem);
    return this;
  }

  /**
   * Get actIdList
   *
   * @return actIdList
   */
  public List<String> getActIdList() {
    return actIdList;
  }

  public void setActIdList(List<String> actIdList) {
    this.actIdList = actIdList;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
