/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 多版位的审核结果信息
 */
public class AuditSpecStruct {
  @SerializedName("site_set")
  private String siteSet = null;

  @SerializedName("system_status")
  private String systemStatus = null;

  @SerializedName("reject_message")
  private String rejectMessage = null;

  public AuditSpecStruct siteSet(String siteSet) {
    this.siteSet = siteSet;
    return this;
  }

  /**
   * Get siteSet
   *
   * @return siteSet
   */
  public String getSiteSet() {
    return siteSet;
  }

  public void setSiteSet(String siteSet) {
    this.siteSet = siteSet;
  }

  public AuditSpecStruct systemStatus(String systemStatus) {
    this.systemStatus = systemStatus;
    return this;
  }

  /**
   * Get systemStatus
   *
   * @return systemStatus
   */
  public String getSystemStatus() {
    return systemStatus;
  }

  public void setSystemStatus(String systemStatus) {
    this.systemStatus = systemStatus;
  }

  public AuditSpecStruct rejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
    return this;
  }

  /**
   * Get rejectMessage
   *
   * @return rejectMessage
   */
  public String getRejectMessage() {
    return rejectMessage;
  }

  public void setRejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
