/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * 行为兴趣意向定向的行为部分的结构
 */
public class BehaviorStruct {
  @SerializedName("targeting_tags")
  private List<String> targetingTags = null;

  @SerializedName("category_id_list")
  private List<Long> categoryIdList = null;

  @SerializedName("keyword_list")
  private List<String> keywordList = null;

  @SerializedName("scene")
  private List<String> scene = null;

  @SerializedName("time_window")
  private String timeWindow = null;

  @SerializedName("intensity")
  private List<String> intensity = null;

  public BehaviorStruct targetingTags(List<String> targetingTags) {
    this.targetingTags = targetingTags;
    return this;
  }

  public BehaviorStruct addTargetingTagsItem(String targetingTagsItem) {
    if (this.targetingTags == null) {
      this.targetingTags = new ArrayList<String>();
    }
    this.targetingTags.add(targetingTagsItem);
    return this;
  }

  /**
   * Get targetingTags
   *
   * @return targetingTags
   */
  public List<String> getTargetingTags() {
    return targetingTags;
  }

  public void setTargetingTags(List<String> targetingTags) {
    this.targetingTags = targetingTags;
  }

  public BehaviorStruct categoryIdList(List<Long> categoryIdList) {
    this.categoryIdList = categoryIdList;
    return this;
  }

  public BehaviorStruct addCategoryIdListItem(Long categoryIdListItem) {
    if (this.categoryIdList == null) {
      this.categoryIdList = new ArrayList<Long>();
    }
    this.categoryIdList.add(categoryIdListItem);
    return this;
  }

  /**
   * Get categoryIdList
   *
   * @return categoryIdList
   */
  public List<Long> getCategoryIdList() {
    return categoryIdList;
  }

  public void setCategoryIdList(List<Long> categoryIdList) {
    this.categoryIdList = categoryIdList;
  }

  public BehaviorStruct keywordList(List<String> keywordList) {
    this.keywordList = keywordList;
    return this;
  }

  public BehaviorStruct addKeywordListItem(String keywordListItem) {
    if (this.keywordList == null) {
      this.keywordList = new ArrayList<String>();
    }
    this.keywordList.add(keywordListItem);
    return this;
  }

  /**
   * Get keywordList
   *
   * @return keywordList
   */
  public List<String> getKeywordList() {
    return keywordList;
  }

  public void setKeywordList(List<String> keywordList) {
    this.keywordList = keywordList;
  }

  public BehaviorStruct scene(List<String> scene) {
    this.scene = scene;
    return this;
  }

  public BehaviorStruct addSceneItem(String sceneItem) {
    if (this.scene == null) {
      this.scene = new ArrayList<String>();
    }
    this.scene.add(sceneItem);
    return this;
  }

  /**
   * Get scene
   *
   * @return scene
   */
  public List<String> getScene() {
    return scene;
  }

  public void setScene(List<String> scene) {
    this.scene = scene;
  }

  public BehaviorStruct timeWindow(String timeWindow) {
    this.timeWindow = timeWindow;
    return this;
  }

  /**
   * Get timeWindow
   *
   * @return timeWindow
   */
  public String getTimeWindow() {
    return timeWindow;
  }

  public void setTimeWindow(String timeWindow) {
    this.timeWindow = timeWindow;
  }

  public BehaviorStruct intensity(List<String> intensity) {
    this.intensity = intensity;
    return this;
  }

  public BehaviorStruct addIntensityItem(String intensityItem) {
    if (this.intensity == null) {
      this.intensity = new ArrayList<String>();
    }
    this.intensity.add(intensityItem);
    return this;
  }

  /**
   * Get intensity
   *
   * @return intensity
   */
  public List<String> getIntensity() {
    return intensity;
  }

  public void setIntensity(List<String> intensity) {
    this.intensity = intensity;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
