/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * CommonParamExceptionSpec
 */
public class CommonParamExceptionSpec {
  @SerializedName("error_fields")
  private List<String> errorFields = null;

  @SerializedName("error_user_msg")
  private String errorUserMsg = null;

  public CommonParamExceptionSpec errorFields(List<String> errorFields) {
    this.errorFields = errorFields;
    return this;
  }

  public CommonParamExceptionSpec addErrorFieldsItem(String errorFieldsItem) {
    if (this.errorFields == null) {
      this.errorFields = new ArrayList<String>();
    }
    this.errorFields.add(errorFieldsItem);
    return this;
  }

  /**
   * Get errorFields
   *
   * @return errorFields
   */
  public List<String> getErrorFields() {
    return errorFields;
  }

  public void setErrorFields(List<String> errorFields) {
    this.errorFields = errorFields;
  }

  public CommonParamExceptionSpec errorUserMsg(String errorUserMsg) {
    this.errorUserMsg = errorUserMsg;
    return this;
  }

  /**
   * Get errorUserMsg
   *
   * @return errorUserMsg
   */
  public String getErrorUserMsg() {
    return errorUserMsg;
  }

  public void setErrorUserMsg(String errorUserMsg) {
    this.errorUserMsg = errorUserMsg;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
