/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * oCPC/oCPM 优化 ROI 配置
 */
public class DeepConversionWorthSpec {
  @SerializedName("goal")
  private String goal = null;

  @SerializedName("expected_roi")
  private Double expectedRoi = null;

  public DeepConversionWorthSpec goal(String goal) {
    this.goal = goal;
    return this;
  }

  /**
   * Get goal
   *
   * @return goal
   */
  public String getGoal() {
    return goal;
  }

  public void setGoal(String goal) {
    this.goal = goal;
  }

  public DeepConversionWorthSpec expectedRoi(Double expectedRoi) {
    this.expectedRoi = expectedRoi;
    return this;
  }

  /**
   * Get expectedRoi
   *
   * @return expectedRoi
   */
  public Double getExpectedRoi() {
    return expectedRoi;
  }

  public void setExpectedRoi(Double expectedRoi) {
    this.expectedRoi = expectedRoi;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
