/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * 设备品牌型号定向
 */
public class DeviceBrandModel {
  @SerializedName("included_list")
  private List<Long> includedList = null;

  @SerializedName("excluded_list")
  private List<Long> excludedList = null;

  public DeviceBrandModel includedList(List<Long> includedList) {
    this.includedList = includedList;
    return this;
  }

  public DeviceBrandModel addIncludedListItem(Long includedListItem) {
    if (this.includedList == null) {
      this.includedList = new ArrayList<Long>();
    }
    this.includedList.add(includedListItem);
    return this;
  }

  /**
   * Get includedList
   *
   * @return includedList
   */
  public List<Long> getIncludedList() {
    return includedList;
  }

  public void setIncludedList(List<Long> includedList) {
    this.includedList = includedList;
  }

  public DeviceBrandModel excludedList(List<Long> excludedList) {
    this.excludedList = excludedList;
    return this;
  }

  public DeviceBrandModel addExcludedListItem(Long excludedListItem) {
    if (this.excludedList == null) {
      this.excludedList = new ArrayList<Long>();
    }
    this.excludedList.add(excludedListItem);
    return this;
  }

  /**
   * Get excludedList
   *
   * @return excludedList
   */
  public List<Long> getExcludedList() {
    return excludedList;
  }

  public void setExcludedList(List<Long> excludedList) {
    this.excludedList = excludedList;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
