/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 浮层卡片创意内容
 */
public class FloatingZone {
  @SerializedName("floating_zone_switch")
  private Boolean floatingZoneSwitch = null;

  @SerializedName("floating_zone_image_id")
  private String floatingZoneImageId = null;

  @SerializedName("floating_zone_name")
  private String floatingZoneName = null;

  @SerializedName("floating_zone_desc")
  private String floatingZoneDesc = null;

  @SerializedName("floating_zone_button_text")
  private String floatingZoneButtonText = null;

  public FloatingZone floatingZoneSwitch(Boolean floatingZoneSwitch) {
    this.floatingZoneSwitch = floatingZoneSwitch;
    return this;
  }

  /**
   * Get floatingZoneSwitch
   *
   * @return floatingZoneSwitch
   */
  public Boolean isFloatingZoneSwitch() {
    return floatingZoneSwitch;
  }

  public void setFloatingZoneSwitch(Boolean floatingZoneSwitch) {
    this.floatingZoneSwitch = floatingZoneSwitch;
  }

  public FloatingZone floatingZoneImageId(String floatingZoneImageId) {
    this.floatingZoneImageId = floatingZoneImageId;
    return this;
  }

  /**
   * Get floatingZoneImageId
   *
   * @return floatingZoneImageId
   */
  public String getFloatingZoneImageId() {
    return floatingZoneImageId;
  }

  public void setFloatingZoneImageId(String floatingZoneImageId) {
    this.floatingZoneImageId = floatingZoneImageId;
  }

  public FloatingZone floatingZoneName(String floatingZoneName) {
    this.floatingZoneName = floatingZoneName;
    return this;
  }

  /**
   * Get floatingZoneName
   *
   * @return floatingZoneName
   */
  public String getFloatingZoneName() {
    return floatingZoneName;
  }

  public void setFloatingZoneName(String floatingZoneName) {
    this.floatingZoneName = floatingZoneName;
  }

  public FloatingZone floatingZoneDesc(String floatingZoneDesc) {
    this.floatingZoneDesc = floatingZoneDesc;
    return this;
  }

  /**
   * Get floatingZoneDesc
   *
   * @return floatingZoneDesc
   */
  public String getFloatingZoneDesc() {
    return floatingZoneDesc;
  }

  public void setFloatingZoneDesc(String floatingZoneDesc) {
    this.floatingZoneDesc = floatingZoneDesc;
  }

  public FloatingZone floatingZoneButtonText(String floatingZoneButtonText) {
    this.floatingZoneButtonText = floatingZoneButtonText;
    return this;
  }

  /**
   * Get floatingZoneButtonText
   *
   * @return floatingZoneButtonText
   */
  public String getFloatingZoneButtonText() {
    return floatingZoneButtonText;
  }

  public void setFloatingZoneButtonText(String floatingZoneButtonText) {
    this.floatingZoneButtonText = floatingZoneButtonText;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
