/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * 行为兴趣意向定向的兴趣部分
 */
public class Interest {
  @SerializedName("targeting_tags")
  private List<String> targetingTags = null;

  @SerializedName("category_id_list")
  private List<Long> categoryIdList = null;

  @SerializedName("keyword_list")
  private List<String> keywordList = null;

  public Interest targetingTags(List<String> targetingTags) {
    this.targetingTags = targetingTags;
    return this;
  }

  public Interest addTargetingTagsItem(String targetingTagsItem) {
    if (this.targetingTags == null) {
      this.targetingTags = new ArrayList<String>();
    }
    this.targetingTags.add(targetingTagsItem);
    return this;
  }

  /**
   * Get targetingTags
   *
   * @return targetingTags
   */
  public List<String> getTargetingTags() {
    return targetingTags;
  }

  public void setTargetingTags(List<String> targetingTags) {
    this.targetingTags = targetingTags;
  }

  public Interest categoryIdList(List<Long> categoryIdList) {
    this.categoryIdList = categoryIdList;
    return this;
  }

  public Interest addCategoryIdListItem(Long categoryIdListItem) {
    if (this.categoryIdList == null) {
      this.categoryIdList = new ArrayList<Long>();
    }
    this.categoryIdList.add(categoryIdListItem);
    return this;
  }

  /**
   * Get categoryIdList
   *
   * @return categoryIdList
   */
  public List<Long> getCategoryIdList() {
    return categoryIdList;
  }

  public void setCategoryIdList(List<Long> categoryIdList) {
    this.categoryIdList = categoryIdList;
  }

  public Interest keywordList(List<String> keywordList) {
    this.keywordList = keywordList;
    return this;
  }

  public Interest addKeywordListItem(String keywordListItem) {
    if (this.keywordList == null) {
      this.keywordList = new ArrayList<String>();
    }
    this.keywordList.add(keywordListItem);
    return this;
  }

  /**
   * Get keywordList
   *
   * @return keywordList
   */
  public List<String> getKeywordList() {
    return keywordList;
  }

  public void setKeywordList(List<String> keywordList) {
    this.keywordList = keywordList;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
