/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * 行为兴趣意向定向的意向部分
 */
public class Intention {
  @SerializedName("targeting_tags")
  private List<Long> targetingTags = null;

  public Intention targetingTags(List<Long> targetingTags) {
    this.targetingTags = targetingTags;
    return this;
  }

  public Intention addTargetingTagsItem(Long targetingTagsItem) {
    if (this.targetingTags == null) {
      this.targetingTags = new ArrayList<>();
    }
    this.targetingTags.add(targetingTagsItem);
    return this;
  }

  /**
   * Get targetingTags
   *
   * @return targetingTags
   */
  public List<Long> getTargetingTags() {
    return targetingTags;
  }

  public void setTargetingTags(List<Long> targetingTags) {
    this.targetingTags = targetingTags;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
