/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 完整视频结构
 */
public class LongVideoStruct {
  @SerializedName("long_video1")
  private Long longVideo1 = null;

  @SerializedName("long_video2")
  private Long longVideo2 = null;

  public LongVideoStruct longVideo1(Long longVideo1) {
    this.longVideo1 = longVideo1;
    return this;
  }

  /**
   * Get longVideo1
   *
   * @return longVideo1
   */
  public Long getLongVideo1() {
    return longVideo1;
  }

  public void setLongVideo1(Long longVideo1) {
    this.longVideo1 = longVideo1;
  }

  public LongVideoStruct longVideo2(Long longVideo2) {
    this.longVideo2 = longVideo2;
    return this;
  }

  /**
   * Get longVideo2
   *
   * @return longVideo2
   */
  public Long getLongVideo2() {
    return longVideo2;
  }

  public void setLongVideo2(Long longVideo2) {
    this.longVideo2 = longVideo2;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
