/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 小程序启动金更多信息
 */
public class MiniprogramAmount {
  @SerializedName("received_amount")
  private Long receivedAmount = null;

  @SerializedName("used_amount")
  private Long usedAmount = null;

  @SerializedName("locked_amount")
  private Long lockedAmount = null;

  @SerializedName("repaid_amount")
  private Long repaidAmount = null;

  @SerializedName("need_repay_amount")
  private Long needRepayAmount = null;

  public MiniprogramAmount receivedAmount(Long receivedAmount) {
    this.receivedAmount = receivedAmount;
    return this;
  }

  /**
   * Get receivedAmount
   *
   * @return receivedAmount
   */
  public Long getReceivedAmount() {
    return receivedAmount;
  }

  public void setReceivedAmount(Long receivedAmount) {
    this.receivedAmount = receivedAmount;
  }

  public MiniprogramAmount usedAmount(Long usedAmount) {
    this.usedAmount = usedAmount;
    return this;
  }

  /**
   * Get usedAmount
   *
   * @return usedAmount
   */
  public Long getUsedAmount() {
    return usedAmount;
  }

  public void setUsedAmount(Long usedAmount) {
    this.usedAmount = usedAmount;
  }

  public MiniprogramAmount lockedAmount(Long lockedAmount) {
    this.lockedAmount = lockedAmount;
    return this;
  }

  /**
   * Get lockedAmount
   *
   * @return lockedAmount
   */
  public Long getLockedAmount() {
    return lockedAmount;
  }

  public void setLockedAmount(Long lockedAmount) {
    this.lockedAmount = lockedAmount;
  }

  public MiniprogramAmount repaidAmount(Long repaidAmount) {
    this.repaidAmount = repaidAmount;
    return this;
  }

  /**
   * Get repaidAmount
   *
   * @return repaidAmount
   */
  public Long getRepaidAmount() {
    return repaidAmount;
  }

  public void setRepaidAmount(Long repaidAmount) {
    this.repaidAmount = repaidAmount;
  }

  public MiniprogramAmount needRepayAmount(Long needRepayAmount) {
    this.needRepayAmount = needRepayAmount;
    return this;
  }

  /**
   * Get needRepayAmount
   *
   * @return needRepayAmount
   */
  public Long getNeedRepayAmount() {
    return needRepayAmount;
  }

  public void setNeedRepayAmount(Long needRepayAmount) {
    this.needRepayAmount = needRepayAmount;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
