/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 修改后的创意内容，当且仅当 online_enabled &#x3D; true 时，此字段允许写入
 */
public class RevisedAdcreativeSpec {
  @SerializedName("revised_adcreative_elements")
  private RevisedAdcreativeElements revisedAdcreativeElements = null;

  @SerializedName("revised_page_spec")
  private RevisedPageSpec revisedPageSpec = null;

  public RevisedAdcreativeSpec revisedAdcreativeElements(
          RevisedAdcreativeElements revisedAdcreativeElements) {
    this.revisedAdcreativeElements = revisedAdcreativeElements;
    return this;
  }

  /**
   * Get revisedAdcreativeElements
   *
   * @return revisedAdcreativeElements
   */
  public RevisedAdcreativeElements getRevisedAdcreativeElements() {
    return revisedAdcreativeElements;
  }

  public void setRevisedAdcreativeElements(RevisedAdcreativeElements revisedAdcreativeElements) {
    this.revisedAdcreativeElements = revisedAdcreativeElements;
  }

  public RevisedAdcreativeSpec revisedPageSpec(RevisedPageSpec revisedPageSpec) {
    this.revisedPageSpec = revisedPageSpec;
    return this;
  }

  /**
   * Get revisedPageSpec
   *
   * @return revisedPageSpec
   */
  public RevisedPageSpec getRevisedPageSpec() {
    return revisedPageSpec;
  }

  public void setRevisedPageSpec(RevisedPageSpec revisedPageSpec) {
    this.revisedPageSpec = revisedPageSpec;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
