/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 短视频结构
 */
public class ShortVideoStruct {
  @SerializedName("short_video1")
  private Long shortVideo1 = null;

  @SerializedName("short_video2")
  private Long shortVideo2 = null;

  public ShortVideoStruct shortVideo1(Long shortVideo1) {
    this.shortVideo1 = shortVideo1;
    return this;
  }

  /**
   * Get shortVideo1
   *
   * @return shortVideo1
   */
  public Long getShortVideo1() {
    return shortVideo1;
  }

  public void setShortVideo1(Long shortVideo1) {
    this.shortVideo1 = shortVideo1;
  }

  public ShortVideoStruct shortVideo2(Long shortVideo2) {
    this.shortVideo2 = shortVideo2;
    return this;
  }

  /**
   * Get shortVideo2
   *
   * @return shortVideo2
   */
  public Long getShortVideo2() {
    return shortVideo2;
  }

  public void setShortVideo2(Long shortVideo2) {
    this.shortVideo2 = shortVideo2;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
