/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * 版位调价
 */
public class SiteSetPackageStruct {
  @SerializedName("site_set")
  private List<String> siteSet = null;

  @SerializedName("bid_coefficient")
  private Double bidCoefficient = null;

  @SerializedName("deep_bid_coefficient")
  private Double deepBidCoefficient = null;

  public SiteSetPackageStruct siteSet(List<String> siteSet) {
    this.siteSet = siteSet;
    return this;
  }

  public SiteSetPackageStruct addSiteSetItem(String siteSetItem) {
    if (this.siteSet == null) {
      this.siteSet = new ArrayList<String>();
    }
    this.siteSet.add(siteSetItem);
    return this;
  }

  /**
   * Get siteSet
   *
   * @return siteSet
   */
  public List<String> getSiteSet() {
    return siteSet;
  }

  public void setSiteSet(List<String> siteSet) {
    this.siteSet = siteSet;
  }

  public SiteSetPackageStruct bidCoefficient(Double bidCoefficient) {
    this.bidCoefficient = bidCoefficient;
    return this;
  }

  /**
   * Get bidCoefficient
   *
   * @return bidCoefficient
   */
  public Double getBidCoefficient() {
    return bidCoefficient;
  }

  public void setBidCoefficient(Double bidCoefficient) {
    this.bidCoefficient = bidCoefficient;
  }

  public SiteSetPackageStruct deepBidCoefficient(Double deepBidCoefficient) {
    this.deepBidCoefficient = deepBidCoefficient;
    return this;
  }

  /**
   * Get deepBidCoefficient
   *
   * @return deepBidCoefficient
   */
  public Double getDeepBidCoefficient() {
    return deepBidCoefficient;
  }

  public void setDeepBidCoefficient(Double deepBidCoefficient) {
    this.deepBidCoefficient = deepBidCoefficient;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
