/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.common;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 温度信息结构
 */
public class TemperatureStruct {
  @SerializedName("min")
  private Long min = null;

  @SerializedName("max")
  private Long max = null;

  public TemperatureStruct min(Long min) {
    this.min = min;
    return this;
  }

  /**
   * Get min
   *
   * @return min
   */
  public Long getMin() {
    return min;
  }

  public void setMin(Long min) {
    this.min = min;
  }

  public TemperatureStruct max(Long max) {
    this.max = max;
    return this;
  }

  /**
   * Get max
   *
   * @return max
   */
  public Long getMax() {
    return max;
  }

  public void setMax(Long max) {
    this.max = max;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
