/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.campaigns;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.tencent.bean.TokenKey;

/**
 * CampaignsUpdateRequest
 */
public class CampaignsUpdateRequest implements TokenKey {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("campaign_id")
  private Long campaignId = null;

  @SerializedName("campaign_name")
  private String campaignName = null;

  @SerializedName("daily_budget")
  private Long dailyBudget = null;

  @SerializedName("configured_status")
  private String configuredStatus = null;

  @SerializedName("speed_mode")
  private String speedMode = null;

  @SerializedName("begin_date")
  private String beginDate = null;

  @SerializedName("end_date")
  private String endDate = null;

  @SerializedName("is_auto_replenish")
  private Long isAutoReplenish = null;

  public CampaignsUpdateRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public CampaignsUpdateRequest campaignId(Long campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * Get campaignId
   *
   * @return campaignId
   */
  public Long getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(Long campaignId) {
    this.campaignId = campaignId;
  }

  public CampaignsUpdateRequest campaignName(String campaignName) {
    this.campaignName = campaignName;
    return this;
  }

  /**
   * Get campaignName
   *
   * @return campaignName
   */
  public String getCampaignName() {
    return campaignName;
  }

  public void setCampaignName(String campaignName) {
    this.campaignName = campaignName;
  }

  public CampaignsUpdateRequest dailyBudget(Long dailyBudget) {
    this.dailyBudget = dailyBudget;
    return this;
  }

  /**
   * Get dailyBudget
   *
   * @return dailyBudget
   */
  public Long getDailyBudget() {
    return dailyBudget;
  }

  public void setDailyBudget(Long dailyBudget) {
    this.dailyBudget = dailyBudget;
  }

  public CampaignsUpdateRequest configuredStatus(String configuredStatus) {
    this.configuredStatus = configuredStatus;
    return this;
  }

  /**
   * Get configuredStatus
   *
   * @return configuredStatus
   */
  public String getConfiguredStatus() {
    return configuredStatus;
  }

  public void setConfiguredStatus(String configuredStatus) {
    this.configuredStatus = configuredStatus;
  }

  public CampaignsUpdateRequest speedMode(String speedMode) {
    this.speedMode = speedMode;
    return this;
  }

  /**
   * Get speedMode
   *
   * @return speedMode
   */
  public String getSpeedMode() {
    return speedMode;
  }

  public void setSpeedMode(String speedMode) {
    this.speedMode = speedMode;
  }

  public CampaignsUpdateRequest beginDate(String beginDate) {
    this.beginDate = beginDate;
    return this;
  }

  /**
   * Get beginDate
   *
   * @return beginDate
   */
  public String getBeginDate() {
    return beginDate;
  }

  public void setBeginDate(String beginDate) {
    this.beginDate = beginDate;
  }

  public CampaignsUpdateRequest endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Get endDate
   *
   * @return endDate
   */
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public CampaignsUpdateRequest isAutoReplenish(Long isAutoReplenish) {
    this.isAutoReplenish = isAutoReplenish;
    return this;
  }

  /**
   * Get isAutoReplenish
   *
   * @return isAutoReplenish
   */
  public Long getIsAutoReplenish() {
    return isAutoReplenish;
  }

  public void setIsAutoReplenish(Long isAutoReplenish) {
    this.isAutoReplenish = isAutoReplenish;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  @Override
  public String getTokenKey() {
    return String.valueOf(accountId);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
