/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.account.funds;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 微信账户更多信息
 */
public class WechatFundSpec {
  @SerializedName("usable_amount")
  private Long usableAmount = null;

  @SerializedName("locked_amount")
  private Long lockedAmount = null;

  public WechatFundSpec usableAmount(Long usableAmount) {
    this.usableAmount = usableAmount;
    return this;
  }

  /**
   * Get usableAmount
   *
   * @return usableAmount
   */
  public Long getUsableAmount() {
    return usableAmount;
  }

  public void setUsableAmount(Long usableAmount) {
    this.usableAmount = usableAmount;
  }

  public WechatFundSpec lockedAmount(Long lockedAmount) {
    this.lockedAmount = lockedAmount;
    return this;
  }

  /**
   * Get lockedAmount
   *
   * @return lockedAmount
   */
  public Long getLockedAmount() {
    return lockedAmount;
  }

  public void setLockedAmount(Long lockedAmount) {
    this.lockedAmount = lockedAmount;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
