/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.wechat_funds;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

/**
 * 更多信息
 */
public class Memo {
  @SerializedName("wechat_fund_spec")
  private WechatFundSpec wechatFundSpec = null;

  public Memo wechatFundSpec(WechatFundSpec wechatFundSpec) {
    this.wechatFundSpec = wechatFundSpec;
    return this;
  }

  /**
   * Get wechatFundSpec
   *
   * @return wechatFundSpec
   */
  public WechatFundSpec getWechatFundSpec() {
    return wechatFundSpec;
  }

  public void setWechatFundSpec(WechatFundSpec wechatFundSpec) {
    this.wechatFundSpec = wechatFundSpec;
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
